import Footer from "@/src/components/Footer";
import Header from "@/src/components/Header";
import StickyFooter from "@/src/components/StickyFooter";
import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <StickyFooter />
      </body>
    </html>
  );
}
